// src/content/salmosContent.ts

interface LocalChapterContent {
  chapter_number: number;
  bible_text: string;
  explanation: string;
  application: string;
}

interface LocalStudyContent {
  [studyKey: string]: LocalChapterContent[];
}

// Use um studyKey que você possa associar ao ID do seu estudo '150 Salmos Explicados' no banco de dados.
// Por exemplo, se o título do estudo for "150 Salmos Explicados", você pode usar uma versão 'slug' dele.
// Para este exemplo, usaremos "150-salmos-explicados".
export const localStudyContent: LocalStudyContent = {
  "150-salmos-explicados": [
    {
      chapter_number: 1,
      bible_text: `Bem-aventurado o homem que não anda segundo o conselho dos ímpios, nem se detém no caminho dos pecadores, nem se assenta na roda dos escarnecedores. Antes tem o seu prazer na lei do Senhor, e na sua lei medita de dia e de noite. Pois será como a árvore plantada junto a ribeiros de águas, a qual dá o seu fruto no seu tempo; as suas folhas não caem, e tudo quanto fizer prosperará. Não são assim os ímpios; mas são como a moinha que o vento espalha. Por isso os ímpios não subsistirão no juízo, nem os pecadores na congregação dos justos. Porque o Senhor conhece o caminho dos justos; mas o caminho dos ímpios perecerá.`,
      explanation: `O Salmo 1 serve como uma introdução a todo o livro dos Salmos, apresentando um contraste fundamental entre dois caminhos de vida: o do justo e o do ímpio. O justo é aquele que se deleita na lei de Deus, meditando nela constantemente, e é comparado a uma árvore frondosa e frutífera, firmemente plantada e próspera. Sua vida é estável e abençoada. Em contrapartida, o ímpio é descrito como a palha levada pelo vento, sem substância, sem estabilidade e sem futuro. O salmo enfatiza que Deus conhece e aprova o caminho dos justos, mas o caminho dos ímpios leva à destruição.`,
      application: `Avalie seus hábitos diários: onde você busca conselho? Com quem você passa seu tempo? Onde está o seu prazer? Dedique tempo à Palavra de Deus, meditando nela para que suas raízes se aprofundem e você possa dar frutos em todas as estações da vida. Afaste-se de influências que o desviam do caminho de Deus e busque a companhia daqueles que o encorajam na fé.`,
    },
    {
      chapter_number: 2,
      bible_text: `Por que se amotinam as nações e os povos tramam em vão? Os reis da terra se levantam, e os príncipes conspiram contra o Senhor e contra o seu Ungido, dizendo: 'Rompamos as suas cadeias e sacudamos de nós as suas algemas!' Aquele que se assenta nos céus se ri; o Senhor zomba deles. Então lhes falará na sua ira e no seu furor os confundirá, dizendo: 'Eu, porém, constituí o meu Rei sobre o meu santo monte Sião.' Proclamarei o decreto do Senhor; ele me disse: 'Tu és meu Filho, eu hoje te gerei. Pede-me, e eu te darei as nações por herança e as extremidades da terra por tua possessão. Tu os esmagarás com uma vara de ferro; tu os despedaçarás como a um vaso de oleiro.' Agora, pois, ó reis, sede prudentes; deixai-vos advertir, ó juízes da terra. Servi ao Senhor com temor e alegrai-vos com tremor. Beijai o Filho, para que não se ire e pereçais no caminho, quando em breve se acender a sua ira. Bem-aventurados todos aqueles que nele confiam.`,
      explanation: `O Salmo 2 é um salmo messiânico que descreve a rebelião das nações contra Deus e seu Messias (o Ungido), e a resposta soberana de Deus a essa rebelião. As nações e seus líderes tentam quebrar as "cadeias" e "algemas" da autoridade divina, mas Deus, do seu trono celestial, ri e zomba de seus esforços fúteis. Ele declara que já estabeleceu seu Rei (o Messias) em Sião. O salmo então apresenta o decreto divino, onde o Messias é declarado Filho de Deus e recebe as nações como herança. A advertência final é para que os reis e juízes se submetam ao Filho, servindo ao Senhor com temor e alegria, pois a ira do Messias é iminente, mas a confiança Nele traz bem-aventurança.`,
      application: `Em um mundo que muitas vezes se rebela contra os princípios de Deus, este salmo nos lembra da soberania divina. Reconheça a autoridade de Cristo em sua vida e sobre o mundo. Em vez de resistir à vontade de Deus, submeta-se a Ele com humildade e alegria. Confie que, apesar das aparências, Deus está no controle e Seu plano prevalecerá. Busque a bem-aventurança que vem de confiar plenamente no Filho.`,
    },
    {
      chapter_number: 3,
      bible_text: `Senhor, como se têm multiplicado os meus adversários! Muitos se levantam contra mim. Muitos dizem da minha alma: 'Não há salvação para ele em Deus.' (Selá) Mas tu, Senhor, és um escudo para mim, a minha glória, e o que exalta a minha cabeça. Com a minha voz clamo ao Senhor, e ele me responde do seu santo monte. (Selá) Eu me deitei e dormi; acordei, porque o Senhor me sustentou. Não temerei dez milhares de pessoas que se puseram contra mim ao redor. Levanta-te, Senhor! Salva-me, Deus meu! Pois feriste a todos os meus inimigos no queixo; quebraste os dentes dos ímpios. A salvação vem do Senhor; sobre o teu povo seja a tua bênção. (Selá)`,
      explanation: `O Salmo 3 é um salmo de lamentação e confiança, escrito por Davi quando fugia de seu filho Absalão. Ele expressa a angústia de Davi diante de muitos inimigos que o cercavam e zombavam de sua fé, dizendo que Deus não o salvaria. No entanto, Davi rapidamente se volta para Deus com confiança, declarando que o Senhor é seu escudo, sua glória e aquele que o levanta. Ele testifica que Deus o ouve e o sustenta, permitindo-lhe dormir em paz e acordar seguro. A confiança de Davi é tão grande que ele não teme multidões de adversários. O salmo termina com uma declaração de fé na salvação que vem do Senhor e um pedido de bênção sobre o povo de Deus.`,
      application: `Em momentos de grande adversidade, quando parece que todos estão contra você e sua fé é questionada, lembre-se do exemplo de Davi. Clame ao Senhor, confie que Ele é seu escudo e sua glória. Permita que a presença de Deus lhe traga paz para descansar, mesmo em meio à tempestade. Não se deixe intimidar pelas vozes que duvidam da sua salvação ou da ajuda de Deus. Declare sua confiança no Senhor, pois a salvação e a bênção vêm d'Ele.`,
    },
    {
      chapter_number: 4,
      bible_text: `Responde-me quando clamo, ó Deus da minha justiça! Na angústia me deste desafogo; tem misericórdia de mim e ouve a minha oração. Ó filhos dos homens, até quando convertereis a minha glória em infâmia? Até quando amareis a vaidade e buscareis a mentira? (Selá) Sabei, porém, que o Senhor separou para si aquele que é piedoso; o Senhor ouvirá quando eu clamar a ele. Tremei e não pequeis; consultai no vosso coração, sobre o vosso leito, e calai. (Selá) Oferecei sacrifícios de justiça e confiai no Senhor. Muitos dizem: 'Quem nos mostrará o bem?' Levanta sobre nós, Senhor, a luz do teu rosto. Puseste alegria no meu coração, mais do que no tempo em que se lhes multiplicaram o trigo e o vinho. Em paz me deito e logo durmo, porque só tu, Senhor, me fazes habitar em segurança.`,
      explanation: `O Salmo 4 é uma oração noturna de Davi, expressando confiança em Deus em meio à adversidade e à oposição. Davi clama a Deus, seu "Deus da justiça", pedindo que o ouça e lhe dê alívio. Ele repreende aqueles que buscam a vaidade e a mentira, contrastando-os com o piedoso que o Senhor separou para si. O salmo exorta à reflexão e ao arrependimento ("Tremei e não pequeis"), incentivando a oferecer sacrifícios de justiça e a confiar no Senhor. Davi testemunha que Deus colocou alegria em seu coração, uma alegria maior do que a prosperidade material, e que ele pode dormir em paz e segurança porque o Senhor o sustenta.`,
      application: `Quando a angústia bater à sua porta ou a injustiça parecer prevalecer, lembre-se de clamar a Deus, o Deus da sua justiça. Não se deixe levar pela busca de coisas vãs ou pela mentira. Em vez disso, reflita sobre suas ações, arrependa-se de seus pecados e confie plenamente no Senhor. Busque a alegria que vem da presença de Deus, que é mais profunda e duradoura do que qualquer bem material. Encontre descanso e segurança em saber que é o Senhor quem o faz habitar em paz.`,
    },
    {
      chapter_number: 5,
      bible_text: `Dá ouvidos às minhas palavras, ó Senhor; atende à minha meditação. Escuta a voz do meu clamor, Rei meu e Deus meu, pois a ti orarei. Pela manhã ouvirás a minha voz, ó Senhor; pela manhã me apresentarei a ti e vigiarei. Porque tu não és um Deus que tenha prazer na iniquidade, nem contigo habitará o mal. Os loucos não pararão à tua vista; odeias a todos os que praticam a maldade. Destróis aqueles que proferem a mentira; o Senhor abomina o homem sanguinário e fraudulento. Mas eu, pela grandeza da tua benignidade, entrarei em tua casa; e em teu temor me inclinarei para o teu santo templo. Guia-me, Senhor, na tua justiça, por causa dos meus inimigos; endireita diante de mim o teu caminho. Porque não há retidão na boca deles; o seu interior está cheio de malícia; a sua garganta é um sepulcro aberto; com a língua lisonjeiam. Declara-os culpados, ó Deus; caiam por seus próprios conselhos; lança-os fora por causa da multidão de suas transgressões, pois se rebelaram contra ti. Mas alegrem-se todos os que confiam em ti; exultem eternamente, porquanto tu os defendes; e em ti se gloriem os que amam o teu nome. Pois tu, Senhor, abençoarás o justo; com a tua benevolência o cercarás como de um escudo.`,
      explanation: `O Salmo 5 é uma oração matinal de Davi, onde ele busca a Deus por orientação e proteção contra seus inimigos. Davi começa pedindo a Deus que ouça sua oração e meditação, expressando sua intenção de buscar o Senhor logo pela manhã. Ele fundamenta seu pedido na natureza santa de Deus, que não tolera a iniquidade, o mal, a loucura, a maldade, a mentira, a violência e a fraude. Em contraste com os ímpios, Davi declara que, pela benignidade de Deus, ele pode entrar em Sua casa e adorar. Ele pede a Deus que o guie em justiça e endireite seu caminho, especialmente por causa de seus inimigos, cujas palavras e intenções são perversas. O salmo conclui com um pedido de condenação para os ímpios e uma declaração de alegria e bênção para aqueles que confiam e amam o nome do Senhor, pois Ele os defende e os cerca com Sua benevolência.`,
      application: `Comece seu dia buscando a Deus em oração, apresentando suas preocupações e pedindo Sua direção. Lembre-se da santidade de Deus e do Seu ódio pelo pecado, o que deve nos motivar a viver em retidão. Confie na benignidade de Deus para se aproximar Dele e peça que Ele o guie em justiça, especialmente quando enfrentar oposição ou tentações. Alegre-se na certeza de que o Senhor defende aqueles que Nele confiam e os abençoa com Sua proteção.`,
    },
    {
      chapter_number: 6,
      bible_text: `Senhor, não me repreendas na tua ira, nem me castigues no teu furor. Tem misericórdia de mim, Senhor, porque sou fraco; sara-me, Senhor, porque os meus ossos estão perturbados. Também a minha alma está muito perturbada; mas tu, Senhor, até quando? Volta-te, Senhor, livra a minha alma; salva-me por tua benignidade. Porque na morte não há lembrança de ti; no sepulcro quem te louvará? Já estou cansado do meu gemido; toda a noite faço nadar a minha cama; molho o meu leito com as minhas lágrimas. Já os meus olhos estão consumidos pela mágoa, e têm envelhecido por causa de todos os meus inimigos. Apartai-vos de mim, todos os que praticais a iniquidade, porque o Senhor já ouviu a voz do meu pranto. O Senhor já ouviu a minha súplica; o Senhor aceitará a minha oração. Envergonhem-se e perturbem-se grandemente todos os meus inimigos; tornem atrás e envergonhem-se num momento.`,
      explanation: `O Salmo 6 é um salmo de lamentação individual, onde Davi expressa profunda angústia física e emocional, clamando a Deus por misericórdia e cura. Ele pede a Deus que não o repreenda em Sua ira, reconhecendo sua fraqueza e a perturbação de seus ossos e alma. A intensidade de seu sofrimento é tal que ele chora a noite toda, molhando seu leito com lágrimas e sentindo seus olhos consumidos pela mágoa, causada por seus inimigos. Davi argumenta que, se morrer, não poderá louvar a Deus no sepulcro, apelando à benignidade divina para ser salvo. No final, há uma mudança abrupta de tom, de lamento para uma declaração de fé e certeza de que Deus ouviu seu clamor e aceitará sua oração, e que seus inimigos serão envergonhados.`,
      application: `Em momentos de profunda dor, seja física ou emocional, este salmo nos encoraja a clamar a Deus com honestidade sobre nossa fraqueza e sofrimento. Não hesite em derramar suas lágrimas diante do Senhor, pois Ele ouve o seu pranto. Lembre-se que a misericórdia de Deus é maior que qualquer ira e que Ele deseja nos curar e nos livrar. Mesmo quando a situação parece desesperadora, mantenha a fé de que Deus ouve suas súplicas e responderá, trazendo vergonha aos seus adversários e alívio para sua alma.`,
    },
    {
      chapter_number: 7,
      bible_text: `Senhor, meu Deus, em ti confio; salva-me de todos os que me perseguem e livra-me; para que não arrebate a minha alma, como leão, despedaçando-a, sem que haja quem a livre. Senhor, meu Deus, se eu fiz isto, se há injustiça nas minhas mãos, se paguei com o mal àquele que tinha paz comigo (antes, livrei ao que me oprimia sem causa), persiga o inimigo a minha alma e alcance-a; pise a minha vida no chão e reduza a pó a minha glória. (Selá) Levanta-te, Senhor, na tua ira; ergue-te contra o furor dos meus adversários; desperta por mim para o juízo que ordenaste. Assim te rodeará o ajuntamento de povos; por causa deles, pois, volta-te para as alturas. O Senhor julgará os povos; julga-me, Senhor, conforme a minha justiça e conforme a integridade que há em mim. Cesse, eu te rogo, a maldade dos ímpios, mas estabelece tu o justo; pois tu, ó justo Deus, provas os corações e os rins. O meu escudo está em Deus, que salva os retos de coração. Deus é juiz justo, e Deus que sente indignação todos os dias. Se o homem não se converter, afiará a sua espada; já tem armado o seu arco e está aparelhado. E já para ele preparou armas mortíferas; e porá em ação as suas setas inflamadas. Eis que o ímpio está com dores de iniquidade; concebeu o mal e deu à luz a falsidade. Cavou um poço e o fez profundo, e caiu na cova que fez. A sua maldade recairá sobre a sua cabeça, e a sua violência descerá sobre a sua própria coroa. Eu louvarei ao Senhor segundo a sua justiça e cantarei louvores ao nome do Senhor Altíssimo.`,
      explanation: `O Salmo 7 é uma oração de Davi pedindo a Deus que o salve de seus perseguidores, afirmando sua inocência diante das acusações. Davi clama a Deus como seu refúgio e escudo, pedindo que Ele se levante em ira e julgue com justiça. Ele confia que Deus, o justo juiz que sonda corações e mentes, defenderá os retos. O salmo descreve a retribuição divina contra os ímpios, que concebem o mal e caem em suas próprias armadilhas. Davi conclui com um louvor ao Senhor por Sua justiça.`,
      application: `Quando você se sentir injustiçado ou perseguido, leve suas causas a Deus em oração, confiando em Sua justiça. Examine seu coração e suas ações, buscando viver com integridade. Lembre-se que Deus é o juiz supremo e que Ele defende os que são retos de coração. Confie que, no tempo certo, a justiça prevalecerá e que aqueles que praticam o mal colherão as consequências de suas próprias ações. Louve a Deus por Sua justiça e soberania.`,
    },
    {
      chapter_number: 8,
      bible_text: `Ó Senhor, Senhor nosso, quão magnífico em toda a terra é o teu nome! Tu puseste a tua glória sobre os céus. Da boca das crianças e dos que mamam tu suscitaste força, por causa dos teus adversários, para fazer calar o inimigo e o vingador. Quando contemplo os teus céus, obra dos teus dedos, a lua e as estrelas que estabeleceste, que é o homem, para que dele te lembres? E o filho do homem, para que o visites? Contudo, pouco menor o fizeste do que os anjos, e de glória e de honra o coroaste. Deste-lhe domínio sobre as obras das tuas mãos; tudo puseste debaixo de seus pés: todas as ovelhas e bois, assim como os animais do campo, as aves do céu e os peixes do mar, e tudo o que passa pelas veredas dos mares. Ó Senhor, Senhor nosso, quão magnífico em toda a terra é o teu nome!`,
      explanation: `O Salmo 8 é um hino de louvor que exalta a majestade de Deus revelada na criação e a dignidade do ser humano. Davi começa e termina o salmo admirando a magnificência do nome de Deus em toda a terra e nos céus. Ele se maravilha com o fato de que Deus usa até mesmo os mais fracos (crianças) para silenciar Seus adversários. Ao contemplar a vastidão do universo, Davi questiona a posição do homem, mas logo reconhece que Deus o coroou de glória e honra, dando-lhe domínio sobre toda a criação.`,
      application: `Reserve um tempo para contemplar a criação de Deus e maravilhar-se com Sua grandeza. Reconheça o valor e a dignidade que Deus lhe concedeu como ser humano, feito à Sua imagem e com domínio sobre a terra. Use essa posição com responsabilidade, cuidando da criação e refletindo a glória de Deus. Lembre-se de que, apesar de nossa pequenez diante do universo, somos preciosos para Deus. Louve-O pela Sua magnificência e pelo Seu cuidado.`,
    },
    {
      chapter_number: 9,
      bible_text: `Eu te louvarei, Senhor, de todo o meu coração; contarei todas as tuas maravilhas. Em ti me alegrarei e exultarei; cantarei louvores ao teu nome, ó Altíssimo. Porquanto os meus inimigos retrocederam, caíram e pereceram diante da tua face. Pois tu tens sustentado o meu direito e a minha causa; tu te assentaste no trono, julgando justamente. Repreendeste as nações, destruíste os ímpios; apagaste o nome deles para sempre e eternamente. Os inimigos foram consumidos, acabaram-se para sempre; e tu destruíste as suas cidades; a sua memória pereceu com eles. Mas o Senhor está assentado perpetuamente; já preparou o seu trono para julgar. Ele julgará o mundo com justiça; julgará os povos com retidão. O Senhor será também um alto refúgio para o oprimido; um alto refúgio em tempos de angústia. Em ti confiarão os que conhecem o teu nome; porque tu, Senhor, nunca desamparaste os que te buscam. Cantai louvores ao Senhor, que habita em Sião; anunciai entre os povos os seus feitos. Pois aquele que vinga o sangue se lembra deles; ele não se esquece do clamor dos aflitos. Tem misericórdia de mim, Senhor; vê a minha aflição, causada por aqueles que me odeiam, tu que me levantas das portas da morte; para que eu conte todos os teus louvores nas portas da filha de Sião e me alegre na tua salvação. Os gentios se afundaram na cova que fizeram; na rede que ocultaram, ficou preso o seu pé. O Senhor é conhecido pelo juízo que faz; enlaçado foi o ímpio na obra de suas próprias mãos. (Higaiom. Selá) Os ímpios serão lançados no inferno, e todas as nações que se esquecem de Deus. Porque o necessitado não será para sempre esquecido, nem a expectação dos pobres perecerá perpetuamente. Levanta-te, Senhor; não prevaleça o homem; sejam julgadas as nações diante de ti. Põe-lhes, Senhor, um terror; saibam as nações que não passam de homens. (Selá)`,
      explanation: `O Salmo 9 é um salmo de ação de graças e confiança na justiça de Deus. Davi louva a Deus de todo o coração por Suas maravilhas e por ter defendido sua causa contra os inimigos. Ele celebra a soberania de Deus como Juiz justo que reprime as nações e destrói os ímpios, enquanto oferece refúgio aos oprimidos. Davi expressa sua confiança de que Deus nunca desampara os que O buscam e que Ele se lembra do clamor dos aflitos. O salmo termina com um apelo para que Deus se levante e julgue as nações, mostrando-lhes que são apenas homens.`,
      application: `Em momentos de vitória ou quando a justiça prevalece, lembre-se de louvar a Deus de todo o seu coração e contar Suas maravilhas. Confie que Deus é um refúgio seguro em tempos de angústia e que Ele nunca desampara aqueles que O buscam. Interceda pelos oprimidos e aflitos, sabendo que Deus se lembra deles. Peça a Deus que Sua justiça seja manifesta no mundo e que todos reconheçam Sua soberania.`,
    },
    {
      chapter_number: 10,
      bible_text: `Por que te pões ao longe, ó Senhor? Por que te escondes nos tempos de angústia? Com arrogância o ímpio persegue o pobre; sejam apanhados nas astutas ciladas que maquinaram. Pois o ímpio gloria-se do desejo da sua alma, e abençoa o avarento, e despreza ao Senhor. Pela altivez do seu rosto, o ímpio não busca a Deus; todas as suas cogitações são: 'Não há Deus.' Os seus caminhos são sempre tortuosos; os teus juízos estão longe da sua vista; quanto a todos os seus adversários, ele assopra contra eles. Diz em seu coração: 'Não serei abalado; nunca me atingirá o mal.' A sua boca está cheia de maldição, de enganos e de opressão; debaixo da sua língua há malícia e iniquidade. Põe-se de emboscada nas aldeias; nos lugares ocultos mata o inocente; os seus olhos estão fixos no pobre. Arma ciladas no esconderijo, como leão no covil; arma ciladas para roubar o pobre; rouba-o, arrastando-o para a sua rede. Abaixa-se, encurva-se, para que os pobres caiam nas suas fortes garras. Diz em seu coração: 'Deus esqueceu-se; cobriu o seu rosto, e nunca o verá.' Levanta-te, Senhor! Ó Deus, levanta a tua mão; não te esqueças dos humildes. Por que despreza o ímpio a Deus? Diz em seu coração: 'Tu não o esquadrinharás.' Tu o vês, porque atentas para o trabalho e a dor, para as retribuir com a tua mão; a ti o pobre se entrega; tu és o amparo do órfão. Quebra o braço do ímpio e do malvado; esquadrinha a sua maldade, até que nenhuma mais encontres. O Senhor é Rei eterno; da sua terra perecerão os gentios. Tu, Senhor, ouves os desejos dos humildes; tu lhes fortalecerás o coração e lhes darás ouvidos, para fazer justiça ao órfão e ao oprimido, a fim de que o homem da terra não mais oprima.`,
      explanation: `O Salmo 10 é um lamento que questiona a aparente ausência de Deus diante da opressão dos ímpios. O salmista descreve a arrogância e a maldade do ímpio, que persegue o pobre, se gloria de seus desejos, despreza a Deus e acredita que não será punido. Ele detalha as ciladas e a violência praticadas pelos ímpios contra os inocentes e os humildes. Em meio a essa descrição sombria, o salmista clama a Deus para que se levante, não se esqueça dos humildes e faça justiça. O salmo termina com uma declaração de confiança na soberania de Deus como Rei eterno, que ouve os desejos dos humildes e fará justiça aos oprimidos.`,
      application: `Quando você testemunhar ou sofrer injustiças e a maldade parecer prevalecer, este salmo o encoraja a clamar a Deus. Não se desespere com a aparente ausência divina, mas lembre-se que Deus vê e ouve o clamor dos humildes. Confie que Ele é o Rei eterno e o Juiz justo que, no tempo certo, quebrará o poder dos ímpios e fará justiça aos oprimidos. Continue a orar por justiça e a ser um amparo para aqueles que são vulneráveis.`,
    },
  ],
  // --- Conteúdo para os Novos Estudos ---
  "parabolas-de-jesus": [
    {
      chapter_number: 1,
      bible_text: `Um semeador saiu a semear. Enquanto lançava a semente, parte dela caiu à beira do caminho, e as aves vieram e a comeram. Parte dela caiu em terreno pedregoso, onde não havia muita terra; e logo brotou, porque a terra não era profunda. Mas, ao nascer do sol, as plantas se queimaram e secaram, porque não tinham raiz. Outra parte caiu entre espinhos, que cresceram e sufocaram as plantas. Outra parte ainda caiu em boa terra, deu boa colheita, a cem, sessenta e trinta por um. Aquele que tem ouvidos para ouvir, ouça!`,
      explanation: `A Parábola do Semeador, encontrada em Mateus 13, Marcos 4 e Lucas 8, ilustra como a Palavra de Deus é recebida por diferentes tipos de corações. As sementes representam a Palavra, e os diferentes solos representam as pessoas. O caminho simboliza aqueles que ouvem, mas não entendem; o terreno pedregoso, os que recebem com alegria, mas não têm profundidade; os espinhos, os que são sufocados pelas preocupações e riquezas; e a boa terra, os que ouvem, entendem e produzem frutos.`,
      application: `Reflita sobre o "solo" do seu coração. Você tem permitido que a Palavra de Deus penetre profundamente, ou ela tem sido superficialmente recebida, sufocada por distrações ou roubada pela incredulidade? Busque um coração receptivo e fértil para que a Palavra de Deus possa crescer e produzir frutos abundantes em sua vida.`,
    },
    {
      chapter_number: 2,
      bible_text: `Jesus continuou: "Um homem tinha dois filhos. O mais novo disse ao pai: 'Pai, quero a minha parte da herança.' Assim, o pai repartiu seus bens entre eles. Não muito tempo depois, o filho mais novo juntou tudo o que tinha e partiu para uma terra distante, onde esbanjou a sua fortuna vivendo irresponsavelmente. Depois de ter gasto tudo, houve uma grande fome naquela região, e ele começou a passar necessidade. Por isso, foi pedir trabalho a um dos cidadãos daquela terra, que o mandou para o campo a fim de cuidar de porcos. Ele desejava encher o estômago com as vagens que os porcos comiam, mas ninguém lhe dava nada. Finalmente, caindo em si, disse: 'Quantos empregados de meu pai têm comida de sobra, e eu aqui, morrendo de fome! Vou voltar para meu pai e dizer: Pai, pequei contra o céu e contra ti. Não sou mais digno de ser chamado teu filho; trata-me como um dos teus empregados.' E assim ele se pôs a caminho e voltou para seu pai. Mas, quando ainda estava longe, seu pai o viu e, cheio de compaixão, correu para o filho, o abraçou e o beijou. O filho lhe disse: 'Pai, pequei contra o céu e contra ti. Não sou mais digno de ser chamado teu filho.' Mas o pai disse aos seus servos: 'Depressa! Tragam a melhor roupa e vistam nele. Ponham um anel em seu dedo e sandálias em seus pés. Tragam o novilho gordo e matem-no. Vamos fazer uma festa e alegrar-nos, pois este meu filho estava morto e voltou à vida; estava perdido e foi achado.' E começaram a festejar.`,
      explanation: `A Parábola do Filho Pródigo (Lucas 15:11-32) é uma das mais conhecidas de Jesus, ilustrando o amor incondicional de Deus e Sua disposição em perdoar e restaurar. O filho mais novo representa o pecador que se afasta de Deus, buscando satisfação em prazeres mundanos, mas acaba em desespero. O pai simboliza Deus, que espera pacientemente, corre ao encontro do filho arrependido e o recebe com festa, sem exigir nada em troca. O filho mais velho, por sua vez, representa aqueles que se consideram justos, mas têm dificuldade em aceitar a graça e a misericórdia de Deus para com os pecadores.`,
      application: `Esta parábola nos convida a refletir sobre nossa própria jornada. Se você se afastou de Deus, saiba que Ele o espera de braços abertos, pronto para perdoar e restaurar. Não importa o quão longe você tenha ido, o arrependimento sincero abre o caminho para o retorno ao lar. Se você se identifica com o filho mais velho, examine seu coração e peça a Deus para cultivar em você um espírito de compaixão e alegria pela salvação dos outros, em vez de julgamento.`,
    },
  ],
  "estudo-do-livro-de-joao": [
    {
      chapter_number: 1,
      bible_text: `No princípio era o Verbo, e o Verbo estava com Deus, e o Verbo era Deus. Ele estava no princípio com Deus. Todas as coisas foram feitas por ele, e sem ele nada do que foi feito se fez. Nele estava a vida, e a vida era a luz dos homens. E a luz resplandece nas trevas, e as trevas não a compreenderam. Houve um homem enviado de Deus, cujo nome era João. Este veio para testemunho, para que testificasse da luz, para que todos cressem por ele. Não era ele a luz, mas para que testificasse da luz. Ali estava a luz verdadeira, que ilumina a todo o homem que vem ao mundo. Estava no mundo, e o mundo foi feito por ele, e o mundo não o conheceu. Veio para o que era seu, e os seus não o receberam. Mas, a todos quantos o receberam, deu-lhes o poder de serem feitos filhos de Deus, aos que creem no seu nome; os quais não nasceram do sangue, nem da vontade da carne, nem da vontade do homem, mas de Deus. E o Verbo se fez carne e habitou entre nós, e vimos a sua glória, como a glória do Unigênito do Pai, cheio de graça e de verdade.`,
      explanation: `O Evangelho de João começa com uma profunda declaração teológica sobre a identidade de Jesus Cristo. Ele é apresentado como o "Verbo" (Logos), que existia com Deus desde o princípio e era Deus. Através d'Ele, todas as coisas foram criadas. João Batista é introduzido como uma testemunha da Luz, que é Jesus. O texto enfatiza que, embora Jesus tenha vindo ao mundo que Ele mesmo criou, muitos não O reconheceram. No entanto, aqueles que O recebem e creem em Seu nome recebem o privilégio de se tornarem filhos de Deus. O ponto culminante é a encarnação: o Verbo eterno se tornou carne e habitou entre nós, revelando a glória de Deus cheia de graça e verdade.`,
      application: `Este capítulo nos convida a contemplar a majestade e a divindade de Jesus. Reconheça que Ele é o Criador e a fonte da vida e da luz. Pergunte a si mesmo: "Eu realmente recebi Jesus em minha vida? Eu creio em Seu nome?" Se sim, celebre o privilégio de ser filho de Deus. Se não, abra seu coração para a Luz verdadeira e permita que a graça e a verdade de Cristo transformem sua vida.`,
    },
    {
      chapter_number: 2,
      bible_text: `Havia um homem fariseu, chamado Nicodemos, príncipe dos judeus. Este foi ter de noite com Jesus e disse-lhe: "Rabi, bem sabemos que és Mestre vindo de Deus, porque ninguém pode fazer estes sinais que tu fazes, se Deus não for com ele." Jesus respondeu e disse-lhe: "Na verdade, na verdade te digo que, se alguém não nascer de novo, não pode ver o Reino de Deus." Disse-lhe Nicodemos: "Como pode um homem nascer, sendo velho? Porventura pode tornar a entrar no ventre de sua mãe e nascer?" Jesus respondeu: "Na verdade, na verdade te digo que, se alguém não nascer da água e do Espírito, não pode entrar no Reino de Deus. O que é nascido da carne é carne, e o que é nascido do Espírito é espírito. Não te maravilhes de eu te haver dito: Necessário vos é nascer de novo. O vento assopra onde quer, e ouves a sua voz, mas não sabes de onde vem, nem para onde vai; assim é todo aquele que é nascido do Espírito."`,
      explanation: `O encontro de Jesus com Nicodemos em João 3 é um diálogo crucial sobre o "novo nascimento". Nicodemos, um líder religioso respeitado, reconhece Jesus como um mestre enviado por Deus, mas não compreende a necessidade de uma transformação espiritual radical. Jesus explica que para "ver" e "entrar" no Reino de Deus, é preciso nascer "de novo", ou seja, nascer "da água e do Espírito". Isso não é um renascimento físico, mas uma obra sobrenatural do Espírito Santo que transforma o coração e a natureza humana, capacitando a pessoa a viver uma nova vida em Deus.`,
      application: `A conversa com Nicodemos nos desafia a ir além do conhecimento religioso e da moralidade externa. Você já experimentou o novo nascimento espiritual? Entende que a salvação não é por obras, mas por uma transformação interior operada pelo Espírito Santo? Peça a Deus para que Ele o faça nascer de novo, para que você possa verdadeiramente ver e viver no Reino de Deus, guiado pelo Espírito.`,
    },
  ],
  "principios-de-lideranca-crista": [
    {
      chapter_number: 1,
      bible_text: `Mas Jesus, chamando-os a si, disse-lhes: "Sabeis que os que são considerados chefes das nações dominam sobre elas, e os seus grandes exercem autoridade sobre elas. Mas entre vós não será assim; pelo contrário, quem quiser tornar-se grande entre vós, será esse o que vos sirva; e quem quiser ser o primeiro entre vós, será servo de todos. Porque o Filho do Homem também não veio para ser servido, mas para servir e dar a sua vida em resgate por muitos." (Marcos 10:42-45)`,
      explanation: `Este capítulo explora o conceito revolucionário de liderança que Jesus apresentou aos seus discípulos. Em contraste com o modelo de liderança mundano, que busca poder, domínio e ser servido, Jesus ensina que a verdadeira grandeza no Reino de Deus reside no serviço. O líder cristão é chamado a ser um servo, seguindo o exemplo do próprio Cristo, que veio para servir e dar a Sua vida. Esta é a essência da liderança cristã: humildade, sacrifício e foco nas necessidades dos outros.`,
      application: `Avalie sua própria abordagem à liderança, seja em casa, no trabalho, na igreja ou em qualquer esfera de influência. Você busca ser servido ou servir? Está disposto a abrir mão de seus próprios interesses para o bem dos outros? Peça a Deus para desenvolver em você um coração de servo, que imita o exemplo de Jesus, buscando impactar e edificar através do serviço humilde.`,
    },
    {
      chapter_number: 2,
      bible_text: `O homem bom tira coisas boas do bom tesouro do seu coração, e o homem mau tira coisas más do seu mau tesouro; porque da abundância do seu coração fala a boca. (Lucas 6:45) Acima de tudo, guarde o seu coração, pois dele procedem as fontes da vida. (Provérbios 4:23)`,
      explanation: `A integridade e o caráter são pilares fundamentais para a liderança cristã. Este capítulo enfatiza que a verdadeira liderança não se baseia apenas em habilidades ou carisma, mas na condição do coração. Jesus ensinou que o que está dentro do coração se manifesta em palavras e ações. Provérbios nos exorta a guardar nosso coração, pois ele é a fonte de tudo o que fazemos. Um líder com integridade é aquele cujas palavras e ações são consistentes com seus valores e com a Palavra de Deus, construindo confiança e credibilidade.`,
      application: `Dedique tempo para examinar seu coração e suas motivações. Há áreas onde sua integridade pode ser fortalecida? Você está guardando seu coração de influências negativas? Busque viver de forma autêntica e transparente, permitindo que o Espírito Santo molde seu caráter para que suas ações e palavras reflitam a bondade e a verdade de Deus. Lembre-se que a liderança eficaz começa com um caráter íntegro.`,
    },
  ],
};